markdown: kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
plugins: [jekyll-paginate]

# Setup
title:            Random Musings
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://monikasymonds.github.io
baseurl:          ''

author:
  name:           'Monika Symonds'
  url:            https://www.instagram.com/branchingcrafts/?hl=en

paginate:         5

# Custom vars
version:          2.1.0


